#-------------------------------
# General Site Settings
title: Kkul-Nyan's GameDevHub
logo: logo.svg # You can add own logo.
description: Kkul-Nyan's GameDevHub


#-------------------------------
# Author Settings
author:
  name: Kkul-Nyan
  image: 01.webp
  say-hello: Hello, Iâ€™m <strong>Kkul-Nyan</strong>
  bio: talks, and writes related to <strong>"GameDev"</strong> like <strong>Shader</strong>, <strong>Algorithm</strong>, <strong>Design Pattern</strong> and . I Loves <span style='color:orange;'>music</span> & <span style='color:orange;'>cat</span>.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle
github:  https://github.com/Kkul-Nyan/


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: noranfoxs-c-shader-and-unity # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-E0RJYF91FR # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
