#-------------------------------
# General Site Settings
title: Noranfox's C#, Shader and Unity
logo: title1.svg # You can add own logo.
description: Nornafox's C#, Shader, Unity Study


#-------------------------------
# Author Settings
author:
  name: Hyeonki jung
  image: main1.jpg
  say-hello: Hello, Iâ€™m <strong>Hyeonki jung</strong>
  bio: talks, and writes about <strong>Shader</strong>, <strong>C#</strong>, <strong>Unity</strong>. Loves <a href="#">music</a> & cat.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
github: https://github.com/noranfox # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-F0BM2DD5RW


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
